spring.application.name=moviereservationsystem
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate
spring.sql.init.mode=always

spring.datasource.url=jdbc:postgresql://localhost:5432/movie_reservation_db
spring.datasource.username=sakethbalijepalli
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver
