spring.application.name=moviereservationsystem
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate
spring.sql.init.mode=always

spring.datasource.url=jdbc:postgresql://localhost:5432/movie_reservation_db
spring.datasource.username=sakethbalijepalli
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

jwt.secret=E6Rn4IOabRK07+xbqBlRUnD9wjdmmmA4syGMASy0owA=
jwt.access-token-expiration-ms=900000
jwt.refresh-token-expiration-ms=604800000

management.endpoints.web.exposure.include=beans,env